version: '3.4'

services:

  edge-proxy:
    image: nginx:1.19.1

  volume:
    - ./nginx/conf.d:/etc/nginx/conf.d/
  networks:
    - edge

  localhost1_1:
    image: renan/route-troubleshooting-api
    environment:
      - APP_NAME= localhost1_INSTANCIA_1
    networks:
      - edge

  localhost1_2:
    image: renan/route-troubleshooting-api
    environment:
      - APP_NAME= localhost1_INSTANCIA_2
    networks:
      - edge

  localhost2:
    image: renan/route-troubleshooting-api
    environment:
      - APP_NAME= localhost2
    networks:
      - edge

networks:
  edge:
    diver: bridge
